[build]
  base = ""
  publish = "public"
  command = "hugo"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.112.3"
  RUBY_VERSION = "2.7.8"
[context.production.environment]
  HUGO_VERSION = "0.112.3"
  RUBY_VERSION = "2.7.8"